spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  security:
    user:
      name: minu
      password: 1234

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${IMAGES}
  jpa:
    hibernate:
      ddl-auto: update
  jooq:
    sql-dialect:
com:
  example:
    upload : ${IMAGES}

#mybatis
mybatis:
  type-aliases-package: com.example.team_project
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/example/team_project/**/*.xml

logging:
  level:
    com.example.team_project.repository.mybatis: trace
  #  mybatis.mapper-location = classpath:mapper/**/*.xml 이렇게 하면 xml 파일을 원하는 위치에 둘 수 있다.