spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/my-db-test
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true

  security:
    user:
      name: minu
      password: 1234